# DishAndDrink.create(name: "Паста Карбонара", grams: 300.0, category: "Food", category_type: "Гарячі страви", price: 150.0)
# DishAndDrink.create(name: "Лосось на грилі з овочами", grams: 250.0 , category: "Food", category_type: "Гарячі страви", price: 200.0)
# DishAndDrink.create(name: "Шашлик з куриці з картошкою фрi", grams: 350.0, category: "Food", category_type: "Гарячі страви", price: 125.0)
# DishAndDrink.create(name: "Чізкейк Нью-Йорк", grams: 230 , category: "Food", category_type: "Десерти", price: 70.0)
# DishAndDrink.create(name: "Піца Маргарита", grams: 450, category: "Food", category_type: "Закуски", price: 330.0)
# DishAndDrink.create(name: "Салат Цезарь з курицею", grams: 320, category: "Food", category_type: "Салати", price: 150.0)
# DishAndDrink.create(name: "Рис з овочами по-азіатскі", grams: 300, category: "Food", category_type: "Гарячі страви", price: 150.0)
# DishAndDrink.create(name: "Суп-гаспачо", grams: 320, category: "Food", category_type: "Гарячі страви", price: 120.0)
# DishAndDrink.create(name: "Фреш апельсиновий", grams: 330, category: "Drink", category_type: "Коктейлі", price: 100)
# DishAndDrink.create(name: "Карамельний латте", grams: 320, category: "Drink", category_type: "Гарячі напої", price: 65)
# DishAndDrink.create(name: "Чай зелений з мятою", grams: 250, category: "Drink", category_type: "Гарячі напої", price: 50)
# DishAndDrink.create(name: "Мартіні сухий", grams: 330, category: "Drink", category_type: "Алкогольні напої", price: 150)
# DishAndDrink.create(name: "Коктейль Піна Колада", grams: 290, category: "Drink", category_type: "Алкогольні напої", price: 150)
# DishAndDrink.create(name: "Еспресо", grams: 220, category: "Drink", category_type: "Гарячі напої", price: 30)
# DishAndDrink.create(name: "Смузі з ягід", grams: 330, category: "Drink", category_type: "Коктейлі", price: 100)

# dish = DishAndDrink.find(1)
# dish1 = DishAndDrink.find(2)
# dish2 = DishAndDrink.find(3)
# dish3 = DishAndDrink.find(4)
# dish4 = DishAndDrink.find(5)
# dish5 = DishAndDrink.find(6)
# dish6 = DishAndDrink.find(7)
# dish7 = DishAndDrink.find(8)
# dish8 = DishAndDrink.find(9)
# dish9 = DishAndDrink.find(10)
# dish10 = DishAndDrink.find(11)
# dish11 = DishAndDrink.find(12)
# dish12 = DishAndDrink.find(13)
# dish13 = DishAndDrink.find(14)
# dish14 = DishAndDrink.find(15)

# # Ingredient.destroy_all
#
# Ingredient.create(dish_and_drink: dish, name: 'Спагеті', grams: '200')
# Ingredient.create(dish_and_drink: dish, name: 'Яйця', grams: '50')
# Ingredient.create(dish_and_drink: dish, name: 'Пармезан', grams: '30')
# Ingredient.create(dish_and_drink: dish, name: 'Бекон', grams: '70')
# Ingredient.create(dish_and_drink: dish, name: 'Часник', grams: '10')
# Ingredient.create(dish_and_drink: dish1, name: 'Лосось', grams: '180')
# Ingredient.create(dish_and_drink: dish1, name: 'Оливкова олія', grams: '10')
# Ingredient.create(dish_and_drink: dish1, name: 'Цукіні', grams: '30')
# Ingredient.create(dish_and_drink: dish1, name: 'Помідори черрі', grams: '20')
# Ingredient.create(dish_and_drink: dish1, name: 'Лимон', grams: '10')
# Ingredient.create(dish_and_drink: dish2, name: 'Куряче філе', grams: '200')
# Ingredient.create(dish_and_drink: dish2, name: 'Картопля', grams: '120')
# Ingredient.create(dish_and_drink: dish2, name: 'Сіль', grams: '5')
# Ingredient.create(dish_and_drink: dish2, name: 'Спеції', grams: '5')
# Ingredient.create(dish_and_drink: dish2, name: 'Олія', grams: '20')
# Ingredient.create(dish_and_drink: dish3, name: 'Сир Філадельфія', grams: '150')
# Ingredient.create(dish_and_drink: dish3, name: 'Яйця', grams: '50')
# Ingredient.create(dish_and_drink: dish3, name: 'Цукор', grams: '30')
# Ingredient.create(dish_and_drink: dish3, name: 'Ваніль', grams: '5')
# Ingredient.create(dish_and_drink: dish3, name: 'Пісочне печиво', grams: '50')
# Ingredient.create(dish_and_drink: dish4, name: 'Тісто для піци', grams: '250')
# Ingredient.create(dish_and_drink: dish4, name: 'Соус томатний', grams: '50')
# Ingredient.create(dish_and_drink: dish4, name: 'Сир моцарела', grams: '100')
# Ingredient.create(dish_and_drink: dish4, name: 'Базилік', grams: '10')
# Ingredient.create(dish_and_drink: dish4, name: 'Оливкова олія', grams: '10')
# Ingredient.create(dish_and_drink: dish5, name: 'Куряче філе', grams: '120')
# Ingredient.create(dish_and_drink: dish5, name: 'Салат ромен', grams: '100')
# Ingredient.create(dish_and_drink: dish5, name: 'Сухарики', grams: '50')
# Ingredient.create(dish_and_drink: dish5, name: 'Сир пармезан', grams: '30')
# Ingredient.create(dish_and_drink: dish5, name: 'Соус Цезар', grams: '20')
# Ingredient.create(dish_and_drink: dish6, name: 'Рис', grams: '200')
# Ingredient.create(dish_and_drink: dish6, name: 'Болгарський перець', grams: '50')
# Ingredient.create(dish_and_drink: dish6, name: 'Гриби', grams: '50')
# Ingredient.create(dish_and_drink: dish6, name: 'Соєвий соус', grams: '20')
# Ingredient.create(dish_and_drink: dish6, name: 'Морква', grams: '30')
# Ingredient.create(dish_and_drink: dish7, name: 'Помідори', grams: '150')
# Ingredient.create(dish_and_drink: dish7, name: 'Огірки', grams: '100')
# Ingredient.create(dish_and_drink: dish7, name: 'Перець', grams: '50')
# Ingredient.create(dish_and_drink: dish7, name: 'Цибуля', grams: '30')
# Ingredient.create(dish_and_drink: dish7, name: 'Оливкова олія', grams: '10')
# Ingredient.create(dish_and_drink: dish8, name: 'Апельсин', grams: '200')
# Ingredient.create(dish_and_drink: dish8, name: 'Цукор', grams: '20')
# Ingredient.create(dish_and_drink: dish8, name: 'Вода', grams: '50')
# Ingredient.create(dish_and_drink: dish8, name: 'Лід', grams: '50')
# Ingredient.create(dish_and_drink: dish9, name: 'Еспресо', grams: '50')
# Ingredient.create(dish_and_drink: dish9, name: 'Молоко', grams: '150')
# Ingredient.create(dish_and_drink: dish9, name: 'Карамельний сироп', grams: '30')
# Ingredient.create(dish_and_drink: dish9, name: 'Цукор', grams: '10')
# Ingredient.create(dish_and_drink: dish9, name: 'Вершки', grams: '50')
# Ingredient.create(dish_and_drink: dish10, name: 'Зелений чай', grams: '100')
# Ingredient.create(dish_and_drink: dish10, name: 'М’ята', grams: '10')
# Ingredient.create(dish_and_drink: dish10, name: 'Лимон', grams: '20')
# Ingredient.create(dish_and_drink: dish10, name: 'Мед', grams: '20')
# Ingredient.create(dish_and_drink: dish10, name: 'Вода', grams: '150')
# Ingredient.create(dish_and_drink: dish11, name: 'Мартіні', grams: '50')
# Ingredient.create(dish_and_drink: dish11, name: 'Оливки', grams: '10')
# Ingredient.create(dish_and_drink: dish11, name: 'Джин', grams: '50')
# Ingredient.create(dish_and_drink: dish11, name: 'Лід', grams: '100')
# Ingredient.create(dish_and_drink: dish11, name: 'Лимон', grams: '10')
# Ingredient.create(dish_and_drink: dish12, name: 'Ром', grams: '50')
# Ingredient.create(dish_and_drink: dish12, name: 'Ананасовий сік', grams: '100')
# Ingredient.create(dish_and_drink: dish12, name: 'Кокосове молоко', grams: '50')
# Ingredient.create(dish_and_drink: dish12, name: 'Лід', grams: '100')
# Ingredient.create(dish_and_drink: dish12, name: 'Цукор', grams: '20')
# Ingredient.create(dish_and_drink: dish13, name: 'Кава', grams: '50')
# Ingredient.create(dish_and_drink: dish13, name: 'Вода', grams: '100')
# Ingredient.create(dish_and_drink: dish13, name: 'Цукор', grams: '10')
# Ingredient.create(dish_and_drink: dish13, name: 'Шоколад', grams: '20')
# Ingredient.create(dish_and_drink: dish13, name: 'Молоко', grams: '50')
# Ingredient.create(dish_and_drink: dish14, name: 'Ягоди', grams: '150')
# Ingredient.create(dish_and_drink: dish14, name: 'Молоко', grams: '100')
# Ingredient.create(dish_and_drink: dish14, name: 'Йогурт', grams: '50')
# Ingredient.create(dish_and_drink: dish14, name: 'Мед', grams: '20')
# Ingredient.create(dish_and_drink: dish14, name: 'Лід', grams: '50')

# # Employee.destroy_all
#
# Employee.create(password: "12345", last_name: "Іванов", first_name: "Іван", parent_name: "Іванович", job_title: "Офіціант", phone_number: "380475652568")
# Employee.create(password: "12345", last_name: "Петров", first_name: "Павел", parent_name: "Сергійович", job_title: "Офіціант", phone_number: "380478762562")
# Employee.create(password: "12345", last_name: "Смирнова", first_name: "Катерина", parent_name: "Олександрівна", job_title: "Офіціант", phone_number: "380645526862")
# Employee.create(password: "12345", last_name: "Козлова", first_name: "Анастасія", parent_name: "Ігорьовна", job_title: "Офіціант", phone_number: "380586546885")
# Employee.create(password: "12345", last_name: "Никитина", first_name: "Марія", parent_name: "Вікторівна", job_title: "Офіціант", phone_number: "380475685965")
# Employee.create(password: "12345", last_name: "Григорьєв", first_name: "Олексій", parent_name: "Дмитрійович", job_title: "Офіціант", phone_number: "380550253695")
# Employee.create(password: "12345", last_name: "Михайлов", first_name: "Артем", parent_name: "Миколайович", job_title: "Офіціант", phone_number: "380641565865")
# Employee.create(password: "12345", last_name: "Кузнецова", first_name: "Валентина", parent_name: "Петрівна", job_title: "Офіціант", phone_number: "380580258685")
# Employee.create(password: "12345", last_name: "Панченко", first_name: "Каріна", parent_name: "Олексіївна", job_title: "Кухар", phone_number: "380652256575")
# Employee.create(password: "12345", last_name: "Клименко", first_name: "Микита", parent_name: "Олександрович", job_title: "Кухар", phone_number: "380568852354")
# Employee.create(password: "12345", last_name: "Неумивака", first_name: "Ульяна", parent_name: "Миколаївна", job_title: "Кухар", phone_number: "380486567414")
# Employee.create(password: "12345", last_name: "Олешко", first_name: "Анастасія", parent_name: "Борисовна", job_title: "Кухар", phone_number: "380588531157")
# Employee.create(password: "12345", last_name: "Костиль", first_name: "Владислава", parent_name: "Володимирівна", job_title: "Кухар", phone_number: "380488856941")
# Employee.create(password: "12345", last_name: "Кравчук", first_name: "Катерина", parent_name: "Андріївна", job_title: "Шеф-кухар", phone_number: "380645862568")
# Employee.create(password: "12345", last_name: "Пономаренко", first_name: "Максим", parent_name: "Вікторович", job_title: "Шеф-кухар", phone_number: "380615283644")
# Employee.create(password: "12345", last_name: "Прохарчук", first_name: "Євген", parent_name: "Анатолійович", job_title: "Керівник", phone_number: "380486582535")

# employee = Employee.find(1)
# employee1 = Employee.find(2)
# employee2 = Employee.find(3)
# employee3 = Employee.find(4)
# employee4 = Employee.find(5)
# employee5 = Employee.find(6)
# employee6 = Employee.find(7)
# employee7 = Employee.find(8)

# Table.create(table_number: 1, link_for_web: "", employee_id: employee.id, client_id: nil)
# Table.create(table_number: 2, link_for_web: "", employee_id: employee1.id, client_id: nil)
# Table.create(table_number: 3, link_for_web: "", employee_id: employee2.id, client_id: nil)
# Table.create(table_number: 4, link_for_web: "", employee_id: employee3.id, client_id: nil)
# Table.create(table_number: 5, link_for_web: "", employee_id: employee4.id, client_id: nil)
# Table.create(table_number: 6, link_for_web: "", employee_id: employee5.id, client_id: nil)
# Table.create(table_number: 7, link_for_web: "", employee_id: employee6.id, client_id: nil)
# Table.create(table_number: 8, link_for_web: "", employee_id: employee7.id, client_id: nil)
#
# table = Table.find(1)

# Order.create(order_id: 97856, table_id: table.id, employee_id: employee.id, dish_status: "готуються", order_status: "Прийнято")
#
# order = Order.find(1)
#
# OrderItem.create(dish_and_drink: dish, order_id: order.id, number_of_dishes: 2)
# OrderItem.create(dish_and_drink: dish7, order_id: order.id, number_of_dishes: 1)
# OrderItem.create(dish_and_drink: dish14, order_id: order.id, number_of_dishes: 2)
# OrderItem.create(dish_and_drink: dish11, order_id: order.id, number_of_dishes: 3)

Client.create(phone_number: "+380980000000", name: "Маріна")